#!/bin/sh
service httpd stop
echo "service stopped"
yum remove httpd -y
echo "service removed"
yum -y install httpd
echo "service installed"
systemctl start httpd
echo "service started"
cd /var/www/html
touch index.html

cat > index.html << EOF


<!DOCTYPE html>
<html>
    <head>
        <title>Hello SoftServe</title>
    </head>
    <body>
        <h1 style="text-align:center">Hello World!</h1>
        <p style="text-align:center">This is a Hello World which is allocated in a EC2 instance created with Terraform and generated by a Shell Script in VM1</p>
        <p style="text-align:center"> Made by: Irene Rojas </p>    
</body>
</html>

EOF